-- GENERATED by tools/build-seed.js from dashboard/data/sample-data.js — do not edit by hand.
-- SAMPLE DATA: real projects, source-linked, not a complete database.
SET search_path = itis, public;
BEGIN;
INSERT INTO lifecycle_status (code, seq, label, phase, pipeline_stage) VALUES
  ('CONCEPT', 1, 'Concept / Proposed', 'PRE', 'PROPOSED'),
  ('FEASIBILITY', 2, 'Feasibility Study', 'PRE', 'PROPOSED'),
  ('DPR_PREPARATION', 3, 'DPR Preparation', 'PRE', 'PROPOSED'),
  ('DPR_COMPLETED', 4, 'DPR Completed', 'PRE', 'DPR'),
  ('CLEARANCES', 5, 'Environmental / Forest / Land Approval', 'PRE', 'APPROVED'),
  ('APPROVED', 6, 'Approved', 'PRE', 'APPROVED'),
  ('TENDER_EXPECTED', 7, 'Tender Expected', 'PRE', 'TENDERED'),
  ('TENDER_ISSUED', 8, 'Tender Issued', 'PRE', 'TENDERED'),
  ('BID_EVALUATION', 9, 'Bid Evaluation', 'PRE', 'TENDERED'),
  ('AWARDED', 10, 'Awarded', 'PRE', 'AWARDED'),
  ('LOA_ISSUED', 11, 'LOA Issued', 'PRE', 'AWARDED'),
  ('FC_PENDING', 12, 'Financial Closure Pending', 'PRE', 'APPROVED'),
  ('LAND_ACQUISITION', 13, 'Land Acquisition / Pre-Construction', 'PRE', 'APPROVED'),
  ('MOBILIZATION', 14, 'Mobilization', 'CON', 'CONSTRUCTION'),
  ('UNDER_CONSTRUCTION', 15, 'Under Construction', 'CON', 'CONSTRUCTION'),
  ('DELAYED', 16, 'Delayed', 'CON', 'CONSTRUCTION'),
  ('STALLED', 17, 'Stalled', 'CON', 'CONSTRUCTION'),
  ('PARTIALLY_OPERATIONAL', 18, 'Partially Operational', 'CON', 'CONSTRUCTION'),
  ('PACKAGE_WISE_CONSTRUCTION', 19, 'Package-wise Construction', 'CON', 'CONSTRUCTION'),
  ('SUBSTANTIALLY_COMPLETED', 20, 'Substantially Completed', 'DONE', 'COMPLETED'),
  ('COMPLETED', 21, 'Completed', 'DONE', 'COMPLETED'),
  ('OPERATIONAL', 22, 'Operational', 'DONE', 'OPERATIONAL'),
  ('OPEN_TO_TRAFFIC', 23, 'Open to Traffic', 'DONE', 'OPERATIONAL'),
  ('CANCELLED', 24, 'Cancelled', 'OTHER', NULL),
  ('TERMINATED', 25, 'Terminated', 'OTHER', NULL),
  ('RE_TENDERED', 26, 'Re-tendered', 'OTHER', 'TENDERED'),
  ('DISPUTED', 27, 'Disputed', 'OTHER', NULL),
  ('UNKNOWN', 28, 'Unknown / Status Requires Verification', 'OTHER', NULL);
INSERT INTO states (state_code, name, kind) VALUES
  ('IN-DL', 'Delhi', 'Union Territory'),
  ('IN-HR', 'Haryana', 'State'),
  ('IN-RJ', 'Rajasthan', 'State'),
  ('IN-MP', 'Madhya Pradesh', 'State'),
  ('IN-GJ', 'Gujarat', 'State'),
  ('IN-MH', 'Maharashtra', 'State'),
  ('IN-JK', 'Jammu & Kashmir', 'Union Territory'),
  ('IN-LA', 'Ladakh', 'Union Territory'),
  ('IN-KA', 'Karnataka', 'State'),
  ('IN-AP', 'Andhra Pradesh', 'State'),
  ('IN-TN', 'Tamil Nadu', 'State'),
  ('IN-UP', 'Uttar Pradesh', 'State'),
  ('IN-AR', 'Arunachal Pradesh', 'State'),
  ('IN-HP', 'Himachal Pradesh', 'State'),
  ('IN-PB', 'Punjab', 'State'),
  ('IN-GA', 'Goa', 'State');
INSERT INTO sources (source_id, url, url_normalised, title, publisher, source_type, tier, pub_date, pub_date_precision, access_date) VALUES
  ('S001', 'https://en.wikipedia.org/wiki/Delhi%E2%80%93Mumbai_Expressway', 'https://en.wikipedia.org/wiki/delhi%e2%80%93mumbai_expressway', 'Delhi–Mumbai Expressway', 'Wikipedia', 'Encyclopedia', 4, NULL, 'unknown', '2026-09-28'),
  ('S002', 'https://swarajyamag.com/infrastructure/delhimumbai-expressway-largely-on-track-for-2026-completion-but-three-gujarat-packages-lag-behind-wont-be-ready-until-march-2028', 'https://swarajyamag.com/infrastructure/delhimumbai-expressway-largely-on-track-for-2026-completion-but-three-gujarat-packages-lag-behind-wont-be-ready-until-march-2028', 'Delhi–Mumbai Expressway largely on track for 2026 completion, but three Gujarat packages lag behind, won''t be ready until March 2028', 'Swarajya', 'News', 3, NULL, 'unknown', '2026-09-28'),
  ('S003', 'https://www.freepressjournal.in/mumbai/samruddhi-mahamarg-final-76-km-stretch-from-igatpuri-to-amane-completed-awaiting-inauguration-for-full-nagpur-mumbai-high-speed-corridor', 'https://www.freepressjournal.in/mumbai/samruddhi-mahamarg-final-76-km-stretch-from-igatpuri-to-amane-completed-awaiting-inauguration-for-full-nagpur-mumbai-high-speed-corridor', 'Samruddhi Mahamarg: final 76 km stretch from Igatpuri to Amane completed', 'Free Press Journal', 'News', 3, NULL, 'unknown', '2026-09-28'),
  ('S004', 'https://www.deccanherald.com/amp/story/india%2Fmaharashtra%2Findias-longest-greenfield-road-project-samruddhi-mahamarg-fully-ready-now-3570712', 'https://www.deccanherald.com/amp/story/india%2fmaharashtra%2findias-longest-greenfield-road-project-samruddhi-mahamarg-fully-ready-now-3570712', 'India''s longest greenfield road project Samruddhi Mahamarg fully ready now', 'Deccan Herald', 'News', 3, '2025-06-01', 'month', '2026-09-28'),
  ('S005', 'https://mmrda.maharashtra.gov.in/projects/transport/mumbai-trans-harbour-link/overview', 'https://mmrda.maharashtra.gov.in/projects/transport/mumbai-trans-harbour-link/overview', 'Mumbai Trans Harbour Link — Overview', 'MMRDA', 'Authority website', 1, NULL, 'unknown', '2026-09-28'),
  ('S006', 'https://en.wikipedia.org/wiki/Mumbai_Trans_Harbour_Link', 'https://en.wikipedia.org/wiki/mumbai_trans_harbour_link', 'Mumbai Trans Harbour Link', 'Wikipedia', 'Encyclopedia', 4, NULL, 'unknown', '2026-09-28'),
  ('S007', 'https://www.tata.com/newsroom/business/atal-setu-mthl-tata-projects', 'https://www.tata.com/newsroom/business/atal-setu-mthl-tata-projects', 'The Bridge over the Harbour (Atal Setu / MTHL — Tata Projects)', 'Tata group', 'Company newsroom', 2, NULL, 'unknown', '2026-09-28'),
  ('S008', 'https://www.tribuneindia.com/news/j-k/zojila-tunnel-project-faces-delay-cost-escalation-completion-pushed-to-2028', 'https://www.tribuneindia.com/news/j-k/zojila-tunnel-project-faces-delay-cost-escalation-completion-pushed-to-2028', 'Zojila tunnel project faces delay, cost escalation; completion pushed to 2028', 'The Tribune', 'News', 3, NULL, 'unknown', '2026-09-28'),
  ('S009', 'https://en.wikipedia.org/wiki/Zoji-la_Tunnel', 'https://en.wikipedia.org/wiki/zoji-la_tunnel', 'Zoji-la Tunnel', 'Wikipedia', 'Encyclopedia', 4, NULL, 'unknown', '2026-09-28'),
  ('S010', 'https://defencera.in/zojila-tunnel-breakthrough-2026/', 'https://defencera.in/zojila-tunnel-breakthrough-2026', 'Zojila Tunnel breakthrough 2026', 'Defencera', 'Blog / portal', 4, '2026-06-01', 'month', '2026-09-28'),
  ('S011', 'https://theprint.in/india/governance/bengaluru-chennai-e-way-meant-to-cut-travel-time-to-3-hrs-set-to-miss-3rd-deadline-due-to-legal-tangle/2958232/', 'https://theprint.in/india/governance/bengaluru-chennai-e-way-meant-to-cut-travel-time-to-3-hrs-set-to-miss-3rd-deadline-due-to-legal-tangle/2958232', 'Bengaluru-Chennai e-way set to miss 3rd deadline due to legal tangle', 'ThePrint', 'News', 3, '2026-01-01', 'year', '2026-09-28'),
  ('S012', 'https://swarajyamag.com/news-brief/bengaluruchennai-expressway-faces-delay-completion-now-expected-by-march-2026', 'https://swarajyamag.com/news-brief/bengaluruchennai-expressway-faces-delay-completion-now-expected-by-march-2026', 'Bengaluru–Chennai Expressway faces delay; completion now expected by March 2026', 'Swarajya', 'News', 3, NULL, 'unknown', '2026-09-28'),
  ('S013', 'https://en.wikipedia.org/wiki/Bengaluru%E2%80%93Chennai_Expressway', 'https://en.wikipedia.org/wiki/bengaluru%e2%80%93chennai_expressway', 'Bengaluru–Chennai Expressway', 'Wikipedia', 'Encyclopedia', 4, NULL, 'unknown', '2026-09-28'),
  ('S014', 'https://en.wikipedia.org/wiki/Coastal_Road_(Mumbai)', 'https://en.wikipedia.org/wiki/coastal_road_(mumbai)', 'Coastal Road (Mumbai)', 'Wikipedia', 'Encyclopedia', 4, NULL, 'unknown', '2026-09-28'),
  ('S015', 'https://www.freepressjournal.in/mumbai/mumbai-news-coastal-road-to-cost-33932-crore-extra', 'https://www.freepressjournal.in/mumbai/mumbai-news-coastal-road-to-cost-33932-crore-extra', 'Mumbai Coastal Road: BMC''s project now costlier by ₹339.32 crore', 'Free Press Journal', 'News', 3, NULL, 'unknown', '2026-09-28'),
  ('S016', 'https://indianinfrastructure.com/2025/01/27/mumbai-coastal-roads-northbound-bridge-to-bandra-worli-sea-link-gets-inaugurated/', 'https://indianinfrastructure.com/2025/01/27/mumbai-coastal-roads-northbound-bridge-to-bandra-worli-sea-link-gets-inaugurated', 'Mumbai Coastal Road''s northbound bridge to Bandra-Worli Sea Link gets inaugurated', 'Indian Infrastructure', 'Trade publication', 3, '2025-01-27', 'day', '2026-09-28'),
  ('S017', 'https://upeida.up.gov.in/en/page/ganga-expressway', 'https://upeida.up.gov.in/en/page/ganga-expressway', 'Ganga Expressway', 'UPEIDA', 'Authority website', 1, NULL, 'unknown', '2026-09-28'),
  ('S018', 'https://www.business-standard.com/amp/economy/news/pm-modi-inaugurates-36-000-crore-ganga-expressway-linking-12-up-districts-126042901330_1.html', 'https://www.business-standard.com/amp/economy/news/pm-modi-inaugurates-36-000-crore-ganga-expressway-linking-12-up-districts-126042901330_1.html', 'PM Modi inaugurates ₹36,000 crore Ganga Expressway linking 12 UP districts', 'Business Standard', 'News', 3, '2026-04-29', 'day', '2026-09-28'),
  ('S019', 'https://www.constructionworld.in/transport-infrastructure/highways-and-roads-infrastructure/ganga-expressway-to-be-built-by-irb-infra-and-adani-group/31318', 'https://www.constructionworld.in/transport-infrastructure/highways-and-roads-infrastructure/ganga-expressway-to-be-built-by-irb-infra-and-adani-group/31318', 'Ganga expressway to be built by IRB Infra and Adani Group', 'Construction World', 'Trade publication', 3, NULL, 'unknown', '2026-09-28'),
  ('S020', 'https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=2012962&reg=48&lang=2', 'https://www.pib.gov.in/pressreleaseiframepage.aspx?prid=2012962&reg=48&lang=2', 'PM virtually dedicates to the nation Sela Tunnel from Itanagar', 'PIB', 'Government press release', 1, '2024-03-09', 'day', '2026-09-28'),
  ('S021', 'https://en.wikipedia.org/wiki/Sela_Tunnel', 'https://en.wikipedia.org/wiki/sela_tunnel', 'Sela Tunnel', 'Wikipedia', 'Encyclopedia', 4, NULL, 'unknown', '2026-09-28'),
  ('S022', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2157088&reg=3&lang=2', 'https://www.pib.gov.in/pressreleasepage.aspx?prid=2157088&reg=3&lang=2', 'PM to inaugurate Delhi section of Dwarka Expressway and UER-II', 'PIB', 'Government press release', 1, '2025-08-01', 'month', '2026-09-28'),
  ('S023', 'https://www.maritimegateway.com/nhai-awards-rs-1047-cr-dwarka-expressway-package-lt/', 'https://www.maritimegateway.com/nhai-awards-rs-1047-cr-dwarka-expressway-package-lt', 'NHAI awards Rs 1,047 cr Dwarka Expressway package to L&T', 'Maritime Gateway', 'Trade publication', 3, NULL, 'unknown', '2026-09-28'),
  ('S024', 'https://www.deccanherald.com/india/haryana/prime-minister-narendra-modi-inaugurates-haryana-section-of-dwarka-expressway-2931049', 'https://www.deccanherald.com/india/haryana/prime-minister-narendra-modi-inaugurates-haryana-section-of-dwarka-expressway-2931049', 'Prime Minister Narendra Modi inaugurates Haryana section of Dwarka Expressway', 'Deccan Herald', 'News', 3, '2024-03-11', 'day', '2026-09-28'),
  ('S025', 'https://www.business-standard.com/india-news/pm-modi-dwarka-expressway-sonipat-uer-ii-delhi-traffic-relief-inauguration-125081600341_1.html', 'https://www.business-standard.com/india-news/pm-modi-dwarka-expressway-sonipat-uer-ii-delhi-traffic-relief-inauguration-125081600341_1.html', 'PM Modi to open new Delhi highways on Aug 17 (Dwarka Expressway, UER-II)', 'Business Standard', 'News', 3, '2025-08-16', 'day', '2026-09-28'),
  ('S026', 'https://www.business-standard.com/india-news/mega-infra-projects-to-make-j-k-one-of-india-s-most-connected-regions-pm-125011301001_1.html', 'https://www.business-standard.com/india-news/mega-infra-projects-to-make-j-k-one-of-india-s-most-connected-regions-pm-125011301001_1.html', 'PM Narendra Modi inaugurates Rs 2,700 crore Z-Morh tunnel in J&K', 'Business Standard', 'News', 3, '2025-01-13', 'day', '2026-09-28'),
  ('S027', 'https://en.wikipedia.org/wiki/Sonamarg_Tunnel', 'https://en.wikipedia.org/wiki/sonamarg_tunnel', 'Sonamarg Tunnel', 'Wikipedia', 'Encyclopedia', 4, NULL, 'unknown', '2026-09-28'),
  ('S028', 'https://www.constructionworld.in/transport-infrastructure/highways-and-roads-infrastructure/hyderabad--39;s-megha-engg-wins-rs-144-bn-thane-borivali-tunnel-tender/40803', 'https://www.constructionworld.in/transport-infrastructure/highways-and-roads-infrastructure/hyderabad--39;s-megha-engg-wins-rs-144-bn-thane-borivali-tunnel-tender/40803', 'Hyderabad''s Megha Engg wins Rs 144 bn Thane-Borivali tunnel tender', 'Construction World', 'Trade publication', 3, NULL, 'unknown', '2026-09-28'),
  ('S029', 'https://mmrda.maharashtra.gov.in/en/TBTthane', 'https://mmrda.maharashtra.gov.in/en/tbtthane', 'Twin Tube Tunnel between Thane and Borivali', 'MMRDA', 'Authority website', 1, NULL, 'unknown', '2026-09-28'),
  ('S030', 'https://meil.in/thane-borivali-tunnel-project', 'https://meil.in/thane-borivali-tunnel-project', 'Thane-Borivali Underground Twin Tube Road Tunnel', 'MEIL', 'Company website', 2, NULL, 'unknown', '2026-09-28'),
  ('S031', 'https://deshgujarat.com/2026/01/19/pune-outer-ring-road-latest-package-wise-progress-update/', 'https://deshgujarat.com/2026/01/19/pune-outer-ring-road-latest-package-wise-progress-update', 'Pune Outer Ring Road: latest package-wise progress update', 'DeshGujarat', 'News', 3, '2026-01-19', 'day', '2026-09-28'),
  ('S032', 'https://urbantransportnews.com/news/five-firms-win-construction-contracts-of-pune-ring-road', 'https://urbantransportnews.com/news/five-firms-win-construction-contracts-of-pune-ring-road', 'Five firms win construction contracts for Pune Ring Road project', 'Urban Transport News', 'Trade publication', 3, NULL, 'unknown', '2026-09-28'),
  ('S033', 'https://marvels.bro.gov.in/AtalTunnel/About', 'https://marvels.bro.gov.in/ataltunnel/about', 'About Us — Atal Tunnel, Rohtang', 'Border Roads Organisation', 'Authority website', 1, NULL, 'unknown', '2026-09-28'),
  ('S034', 'https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=1660559&reg=48&lang=2', 'https://www.pib.gov.in/pressreleaseiframepage.aspx?prid=1660559&reg=48&lang=2', 'Prime Minister to inaugurate the Atal Tunnel', 'PIB', 'Government press release', 1, '2020-10-01', 'month', '2026-09-28'),
  ('S035', 'https://en.wikipedia.org/wiki/Delhi%E2%80%93Amritsar%E2%80%93Katra_Expressway', 'https://en.wikipedia.org/wiki/delhi%e2%80%93amritsar%e2%80%93katra_expressway', 'Delhi–Amritsar–Katra Expressway', 'Wikipedia', 'Encyclopedia', 4, NULL, 'unknown', '2026-09-28'),
  ('S036', 'https://theprint.in/statedraft/delhi-katra-expressway-latest-nhai-project-to-face-land-acquisition-hurdle-in-punjab-theres-15-more/2517200/', 'https://theprint.in/statedraft/delhi-katra-expressway-latest-nhai-project-to-face-land-acquisition-hurdle-in-punjab-theres-15-more/2517200', 'Delhi-Katra expressway''s Amritsar leg not only NHAI project hit by land acquisition hurdles in Punjab', 'ThePrint', 'News', 3, NULL, 'unknown', '2026-09-28'),
  ('S037', 'https://www.businesstoday.in/latest/trends/photo/delhi-to-katra-in-six-hours-and-amritsar-in-four-what-nhais-expressway-travel-time-targets-really-mean-554004-2026-09-08', 'https://www.businesstoday.in/latest/trends/photo/delhi-to-katra-in-six-hours-and-amritsar-in-four-what-nhais-expressway-travel-time-targets-really-mean-554004-2026-09-08', 'Delhi to Katra in six hours and Amritsar in four? What NHAI''s expressway travel-time targets really mean', 'Business Today', 'News', 3, '2026-09-08', 'day', '2026-09-28'),
  ('S038', 'https://en.wikipedia.org/wiki/Shaktipeeth_Expressway', 'https://en.wikipedia.org/wiki/shaktipeeth_expressway', 'Shaktipeeth Expressway', 'Wikipedia', 'Encyclopedia', 4, NULL, 'unknown', '2026-09-28'),
  ('S039', 'https://www.deccanherald.com/india/maharashtra/maharashtra-govt-revives-shaktipeeth-expressway-3429363', 'https://www.deccanherald.com/india/maharashtra/maharashtra-govt-revives-shaktipeeth-expressway-3429363', 'Maharashtra govt revives Shaktipeeth expressway', 'Deccan Herald', 'News', 3, NULL, 'unknown', '2026-09-28'),
  ('S040', 'https://www.infracapitalist.com/project/shaktipeeth-expressway', 'https://www.infracapitalist.com/project/shaktipeeth-expressway', 'Shaktipeeth Expressway: revised alignment, latest news & land acquisition (2026)', 'Infracapitalist', 'Specialist portal', 4, '2026-01-01', 'year', '2026-09-28'),
  ('S041', 'https://www.newsonair.gov.in/maharashtra-cabinet-approves-105-km-freight-corridor-linking-vadhavan-port-to-samruddhi-expressway', 'https://www.newsonair.gov.in/maharashtra-cabinet-approves-105-km-freight-corridor-linking-vadhavan-port-to-samruddhi-expressway', 'Maharashtra cabinet approves 105-km freight corridor linking Vadhavan Port to Samruddhi Expressway', 'News On AIR (Prasar Bharati)', 'Public broadcaster', 1, '2025-08-05', 'day', '2026-09-28'),
  ('S042', 'https://www.blackridgeresearch.com/project-profiles/zohila-tunnel-length-route-cost-contractor-completion-date-status', 'https://www.blackridgeresearch.com/project-profiles/zohila-tunnel-length-route-cost-contractor-completion-date-status', 'Zojila Tunnel project: current status & completion date (2026)', 'Blackridge Research', 'Specialist portal', 4, NULL, 'unknown', '2026-09-28'),
  ('S043', 'https://www.tribuneindia.com/news/j-k/strategic-zojila-tunnel-achieves-major-milestone-less-than-1-km-work-remains/', 'https://www.tribuneindia.com/news/j-k/strategic-zojila-tunnel-achieves-major-milestone-less-than-1-km-work-remains', 'Strategic Zojila tunnel achieves major milestone, less than 1 km work remains', 'The Tribune', 'News', 3, '2026-05-01', 'month', '2026-09-28'),
  ('S044', 'https://en.wikipedia.org/wiki/Ganga_Expressway', 'https://en.wikipedia.org/wiki/ganga_expressway', 'Ganga Expressway', 'Wikipedia', 'Encyclopedia', 4, NULL, 'unknown', '2026-09-28'),
  ('S045', 'https://www.globalhighways.com/wh10/news/sela-tunnel-india-inaugurated', 'https://www.globalhighways.com/wh10/news/sela-tunnel-india-inaugurated', 'Sela Tunnel in India inaugurated', 'Global Highways', 'Trade publication', 3, '2024-03-01', 'month', '2026-09-28'),
  ('S046', 'https://www.newsonair.gov.in/pm-modi-inaugurates-%E2%82%B911000-crore-highway-projects-in-delhi', 'https://www.newsonair.gov.in/pm-modi-inaugurates-%e2%82%b911000-crore-highway-projects-in-delhi', 'PM Modi inaugurates ₹11,000 crore highway projects in Delhi', 'News On AIR (Prasar Bharati)', 'Public broadcaster', 1, '2025-08-17', 'day', '2026-09-28'),
  ('S047', 'https://www.punekarnews.in/msrdc-faces-delay-in-third-party-scrutiny-report-for-pune-ring-road-tenders/', 'https://www.punekarnews.in/msrdc-faces-delay-in-third-party-scrutiny-report-for-pune-ring-road-tenders', 'MSRDC faces delay in third-party scrutiny report for Pune Ring Road tenders', 'Punekar News', 'News', 3, NULL, 'unknown', '2026-09-28'),
  ('S049', 'https://www.blackridgeresearch.com/project-profiles/dwarka-expressway-highway-cost-route-location-completion-date-inauguration/', 'https://www.blackridgeresearch.com/project-profiles/dwarka-expressway-highway-cost-route-location-completion-date-inauguration', 'Dwarka Expressway: route, location, cost & completion date', 'Blackridge Research', 'Specialist portal', 4, NULL, 'unknown', '2026-09-28');
INSERT INTO authorities (authority_id, short_name, legal_name, level, parent_authority_id, website) VALUES
  ('A-MORTH', 'MoRTH', 'Ministry of Road Transport & Highways', 'Central', NULL, 'https://morth.nic.in'),
  ('A-BRO', 'BRO', 'Border Roads Organisation', 'Central (Ministry of Defence)', NULL, 'https://bro.gov.in'),
  ('A-MSRDC', 'MSRDC', 'Maharashtra State Road Development Corporation', 'State (Maharashtra)', NULL, 'https://msrdc.in'),
  ('A-MMRDA', 'MMRDA', 'Mumbai Metropolitan Region Development Authority', 'State (Maharashtra)', NULL, 'https://mmrda.maharashtra.gov.in'),
  ('A-BMC', 'BMC', 'Brihanmumbai Municipal Corporation', 'Municipal', NULL, 'https://portal.mcgm.gov.in'),
  ('A-UPEIDA', 'UPEIDA', 'Uttar Pradesh Expressways Industrial Development Authority', 'State (Uttar Pradesh)', NULL, 'https://upeida.up.gov.in'),
  ('A-NHAI', 'NHAI', 'National Highways Authority of India', 'Central', 'A-MORTH', 'https://nhai.gov.in'),
  ('A-NHIDCL', 'NHIDCL', 'National Highways & Infrastructure Development Corporation Ltd', 'Central', 'A-MORTH', 'https://nhidcl.com');
INSERT INTO authority_aliases (authority_id, alias, alias_norm) VALUES
  ('A-MORTH', 'MoRTH', 'morth'),
  ('A-MORTH', 'Ministry of Road Transport & Highways', 'ministry of road transport highways'),
  ('A-NHAI', 'NHAI', 'nhai'),
  ('A-NHAI', 'National Highways Authority of India', 'national highways authority of india'),
  ('A-NHIDCL', 'NHIDCL', 'nhidcl'),
  ('A-NHIDCL', 'National Highways & Infrastructure Development Corporation Ltd', 'national highways infrastructure development corporation'),
  ('A-BRO', 'BRO', 'bro'),
  ('A-BRO', 'Border Roads Organisation', 'border roads organisation'),
  ('A-MSRDC', 'MSRDC', 'msrdc'),
  ('A-MSRDC', 'Maharashtra State Road Development Corporation', 'maharashtra state road development corporation'),
  ('A-MMRDA', 'MMRDA', 'mmrda'),
  ('A-MMRDA', 'Mumbai Metropolitan Region Development Authority', 'mumbai metropolitan region development authority'),
  ('A-BMC', 'BMC', 'bmc'),
  ('A-BMC', 'Brihanmumbai Municipal Corporation', 'brihanmumbai municipal corporation'),
  ('A-UPEIDA', 'UPEIDA', 'upeida'),
  ('A-UPEIDA', 'Uttar Pradesh Expressways Industrial Development Authority', 'uttar pradesh expressways industrial development authority');
INSERT INTO companies (company_id, canonical_name, listed, country, hq_city, website, kind) VALUES
  ('C-LT', 'Larsen & Toubro Limited', true, 'India', 'Mumbai', 'https://www.larsentoubro.com', 'EPC contractor'),
  ('C-IHI', 'IHI Corporation', true, 'Japan', 'Tokyo', 'https://www.ihi.co.jp', 'EPC / steel structures'),
  ('C-DAEWOO', 'Daewoo Engineering & Construction', true, 'South Korea', 'Seoul', NULL, 'EPC contractor'),
  ('C-TPL', 'Tata Projects Limited', false, 'India', 'Hyderabad', 'https://www.tataprojects.com', 'EPC contractor'),
  ('C-MEIL', 'Megha Engineering & Infrastructures Ltd', false, 'India', 'Hyderabad', 'https://meil.in', 'EPC contractor'),
  ('C-HCC', 'Hindustan Construction Company Ltd', true, 'India', 'Mumbai', 'https://www.hccindia.com', 'EPC contractor'),
  ('C-HDC', 'Hyundai Development Company', NULL, 'South Korea', NULL, NULL, 'EPC contractor'),
  ('C-IRB', 'IRB Infrastructure Developers Ltd', true, 'India', 'Mumbai', 'https://www.irb.co.in', 'Developer / EPC'),
  ('C-ADANI', 'Adani Enterprises Ltd', true, 'India', 'Ahmedabad', 'https://www.adanienterprises.com', 'Developer / EPC'),
  ('C-PATEL', 'Patel Engineering Ltd', true, 'India', 'Mumbai', NULL, 'Tunnel / civil contractor'),
  ('C-JKUMAR', 'J. Kumar Infraprojects Ltd', true, 'India', 'Mumbai', NULL, 'EPC contractor'),
  ('C-APCO', 'APCO Infratech Pvt Ltd', false, 'India', NULL, NULL, 'EPC contractor'),
  ('C-NECL', 'Navayuga Engineering Company Ltd', false, 'India', 'Hyderabad', NULL, 'EPC contractor'),
  ('C-GRIL', 'G R Infraprojects Ltd', true, 'India', NULL, NULL, 'EPC contractor'),
  ('C-PNC', 'PNC Infratech Ltd', true, 'India', NULL, NULL, 'EPC contractor'),
  ('C-RSIIL', 'Roadway Solutions India Infra Ltd', NULL, 'India', NULL, NULL, 'EPC contractor'),
  ('C-STRABAG', 'STRABAG', true, 'Austria', NULL, NULL, 'Tunnel / EPC contractor'),
  ('C-AFCONS', 'Afcons Infrastructure Ltd', true, 'India', 'Mumbai', NULL, 'EPC contractor'),
  ('C-ILFS', 'IL&FS (infrastructure arm)', NULL, 'India', NULL, NULL, 'Former contractor');
INSERT INTO company_aliases (company_id, alias, alias_norm) VALUES
  ('C-LT', 'Larsen & Toubro Limited', 'larsen toubro'),
  ('C-LT', 'L&T', 'l t'),
  ('C-LT', 'Larsen and Toubro', 'larsen and toubro'),
  ('C-IHI', 'IHI Corporation', 'ihi corporation'),
  ('C-IHI', 'IHI', 'ihi'),
  ('C-DAEWOO', 'Daewoo Engineering & Construction', 'daewoo engineering construction'),
  ('C-DAEWOO', 'Daewoo E&C', 'daewoo e c'),
  ('C-DAEWOO', 'Daewoo', 'daewoo'),
  ('C-TPL', 'Tata Projects Limited', 'tata projects'),
  ('C-TPL', 'TPL', 'tpl'),
  ('C-MEIL', 'Megha Engineering & Infrastructures Ltd', 'megha engineering infrastructures'),
  ('C-MEIL', 'MEIL', 'meil'),
  ('C-MEIL', 'Megha Engineering', 'megha engineering'),
  ('C-HCC', 'Hindustan Construction Company Ltd', 'hindustan construction company'),
  ('C-HCC', 'HCC', 'hcc'),
  ('C-HDC', 'Hyundai Development Company', 'hyundai development company'),
  ('C-HDC', 'HDC', 'hdc'),
  ('C-HDC', 'HDC Hyundai Development Company', 'hdc hyundai development company'),
  ('C-IRB', 'IRB Infrastructure Developers Ltd', 'irb infrastructure developers'),
  ('C-IRB', 'IRB Infra', 'irb infra'),
  ('C-IRB', 'IRB', 'irb'),
  ('C-ADANI', 'Adani Enterprises Ltd', 'adani enterprises'),
  ('C-ADANI', 'Adani Group', 'adani group'),
  ('C-ADANI', 'Adani', 'adani'),
  ('C-PATEL', 'Patel Engineering Ltd', 'patel engineering'),
  ('C-JKUMAR', 'J. Kumar Infraprojects Ltd', 'j kumar infraprojects'),
  ('C-JKUMAR', 'J Kumar', 'j kumar'),
  ('C-APCO', 'APCO Infratech Pvt Ltd', 'apco infratech'),
  ('C-APCO', 'APCO', 'apco'),
  ('C-NECL', 'Navayuga Engineering Company Ltd', 'navayuga engineering company'),
  ('C-NECL', 'Navayuga', 'navayuga'),
  ('C-NECL', 'NECL', 'necl'),
  ('C-GRIL', 'G R Infraprojects Ltd', 'g r infraprojects'),
  ('C-GRIL', 'GR Infra', 'gr infra'),
  ('C-GRIL', 'GRIL', 'gril'),
  ('C-GRIL', 'G R Infra', 'g r infra'),
  ('C-PNC', 'PNC Infratech Ltd', 'pnc infratech'),
  ('C-PNC', 'PNC', 'pnc'),
  ('C-RSIIL', 'Roadway Solutions India Infra Ltd', 'roadway solutions india infra'),
  ('C-RSIIL', 'RSIIL', 'rsiil'),
  ('C-STRABAG', 'STRABAG', 'strabag'),
  ('C-STRABAG', 'STRABAG AG', 'strabag ag'),
  ('C-STRABAG', 'STRABAG SE', 'strabag se'),
  ('C-AFCONS', 'Afcons Infrastructure Ltd', 'afcons infrastructure'),
  ('C-AFCONS', 'AFCONS', 'afcons'),
  ('C-ILFS', 'IL&FS (infrastructure arm)', 'il fs infrastructure arm'),
  ('C-ILFS', 'IL&FS', 'il fs'),
  ('C-ILFS', 'ITNL', 'itnl');
INSERT INTO corridors (corridor_id, name) VALUES
  ('CR-DELHI-MUMBAI', 'Delhi–Mumbai'),
  ('CR-MUMBAI-NAGPUR', 'Mumbai–Nagpur'),
  ('CR-SEWRI-NHAVA-SHEVA', 'Sewri–Nhava Sheva'),
  ('CR-SRINAGAR-LEH', 'Srinagar–Leh'),
  ('CR-BENGALURU-CHENNAI', 'Bengaluru–Chennai'),
  ('CR-MUMBAI-COASTAL-ROAD', 'Mumbai Coastal Road'),
  ('CR-MEERUT-PRAYAGRAJ', 'Meerut–Prayagraj'),
  ('CR-BALIPARA-CHARIDUAR-TAWANG', 'Balipara–Chariduar–Tawang'),
  ('CR-DELHI-GURUGRAM', 'Delhi–Gurugram'),
  ('CR-THANE-BORIVALI', 'Thane–Borivali'),
  ('CR-PUNE-RING-ROAD', 'Pune Ring Road'),
  ('CR-MANALI-LEH', 'Manali–Leh'),
  ('CR-DELHI-AMRITSAR-KATRA', 'Delhi–Amritsar–Katra'),
  ('CR-NAGPUR-GOA', 'Nagpur–Goa'),
  ('CR-VADHAVAN-SAMRUDDHI', 'Vadhavan–Samruddhi');

-- ITI-P-0001 Delhi–Mumbai Expressway
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0001', 'Delhi–Mumbai Expressway', 'Expressway', 'Greenfield access-controlled expressway', 'CR-DELHI-MUMBAI', 'NE-4', 'Bharatmala Pariyojana', 'Delhi', 'Mumbai (JNPT)', 1350, '1,350 km mainline (S001); 54 packages cover 1,445 km incl. spurs (S002)', '8 (expandable to 12) — per S001', 'Mixed', 'National economic corridor', 'A-MORTH', 'A-NHAI', 'REPORTED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0001', 'Delhi Mumbai Expressway', 'delhi mumbai expressway'),
  ('ITI-P-0001', 'DME', 'dme'),
  ('ITI-P-0001', 'Delhi–Mumbai Greenfield Expressway', 'delhi mumbai greenfield expressway');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0001', 'IN-DL', false),
  ('ITI-P-0001', 'IN-HR', false),
  ('ITI-P-0001', 'IN-RJ', true),
  ('ITI-P-0001', 'IN-MP', false),
  ('ITI-P-0001', 'IN-GJ', false),
  ('ITI-P-0001', 'IN-MH', false);
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0001', 96547, 'sanctioned', 'Sanctioned cost', '2025-12-01', 'month', true, 'Most specific whole-project cost reported', NULL, 'REPORTED', 'S002'),
  ('ITI-P-0001', 77558, 'expenditure_to_date', 'Expenditure incurred to Dec-2025', '2025-12-01', 'month', false, NULL, NULL, 'REPORTED', 'S002');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0001', '2025-12-01', 'month', 'opening', 'PARTIALLY_OPERATIONAL', '₹77,558 cr spent of ₹96,547 cr sanctioned; 929 km operational', 'REPORTED', 'S002'),
  ('ITI-P-0001', '2026-01-01', 'year', 'milestone', NULL, 'Package-level delay: three Gujarat packages (Vadodara–Mumbai stretch) pushed to March 2028', 'REPORTED', 'S002');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0001', '2026-01-01', 'year', NULL, '929 km of 1,445 km operationalised; Delhi–Vadodara 697 of 912 km operational (S002)', 'S002');
INSERT INTO delay_risks (project_id, category, description, source_id) VALUES
  ('ITI-P-0001', 'Other', 'Three Gujarat packages lag; cause not specified in captured source', 'S002');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0001', 'schematic', ST_GeomFromText('LINESTRING(77.28 28.57, 77.07 28.25, 76.34 26.89, 76.35 26.02, 75.83 25.18, 75.04 23.33, 74.59 22.77, 73.18 22.31, 72.98 21.7, 72.81 19.46, 72.95 18.95)', 4326), 'APPROXIMATE', 'Town-to-town schematic through reported corridor cities', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0001', 'Tolling / ITS', 'potential', 'Access-controlled tolled expressway (characteristic, not documented here)'),
  ('ITI-P-0001', 'Command & control / CCTV', 'potential', 'Long-length access-controlled corridor');

-- ITI-P-0002 Mumbai–Nagpur Expressway (Samruddhi Mahamarg)
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0002', 'Mumbai–Nagpur Expressway (Samruddhi Mahamarg)', 'Expressway', 'Greenfield access-controlled expressway', 'CR-MUMBAI-NAGPUR', NULL, 'State (Maharashtra)', 'Nagpur', 'Amane (Thane district)', 701, '701 km (S003, S004)', '6', 'Plain / Ghat (Kasara)', 'State economic corridor', NULL, 'A-MSRDC', 'CROSS_VERIFIED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0002', 'Mumbai–Nagpur Expressway (Samruddhi Mahamarg)', 'mumbai nagpur expressway samruddhi mahamarg'),
  ('ITI-P-0002', 'Samruddhi Mahamarg', 'samruddhi mahamarg'),
  ('ITI-P-0002', 'Hindu Hrudaysamrat Balasaheb Thackeray Maharashtra Samruddhi Mahamarg', 'hindu hrudaysamrat balasaheb thackeray maharashtra samruddhi mahamarg'),
  ('ITI-P-0002', 'Mumbai Nagpur Expressway', 'mumbai nagpur expressway');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0002', 'IN-MH', true);
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0002', 55000, 'reported_cost', 'Reported project cost (approx.)', '2025-06-01', 'month', true, 'Most specific whole-project cost reported', NULL, 'REPORTED', 'S004');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0002', '2025-06-05', 'day', 'opening', 'OPERATIONAL', 'Final Igatpuri–Amane stretch inaugurated; full 701 km operational', 'REPORTED', 'S004');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0002', '2025-06-05', 'day', 100, 'Final Igatpuri–Amane 76 km opened 5 Jun 2025', 'S004');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0002', 'schematic', ST_GeomFromText('LINESTRING(79.09 21.15, 78.6 20.74, 77.13 20.11, 75.88 19.84, 75.34 19.88, 74.48 19.77, 73.56 19.7, 73.08 19.3)', 4326), 'APPROXIMATE', 'Town-to-town schematic', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0002', 'Tunnel systems (ventilation/SCADA/fire)', 'potential', 'Reported ~7.8 km road tunnel on corridor');

-- ITI-P-0003 Mumbai Trans Harbour Link (Atal Setu)
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0003', 'Mumbai Trans Harbour Link (Atal Setu)', 'Bridge', 'Sea bridge', 'CR-SEWRI-NHAVA-SHEVA', NULL, 'MMRDA', 'Sewri (Mumbai)', 'Chirle (Navi Mumbai)', 21.8, 'Sum of 3 civil packages: 10.38 + 7.807 + 3.613 km (S006)', '6', 'Marine', 'Metropolitan sea link', NULL, 'A-MMRDA', 'REPORTED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0003', 'Mumbai Trans Harbour Link (Atal Setu)', 'mumbai trans harbour link atal setu'),
  ('ITI-P-0003', 'MTHL', 'mthl'),
  ('ITI-P-0003', 'Atal Bihari Vajpayee Sewri–Nhava Sheva Atal Setu', 'atal bihari vajpayee sewri nhava sheva atal setu'),
  ('ITI-P-0003', 'Atal Setu', 'atal setu');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0003', 'IN-MH', true);
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0003', 'Pkg 1', 'Sewri side marine viaduct', 10.38, NULL, NULL, 'REPORTED', 'S006');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0003' AND package_no='Pkg 1'), 'Unknown', '2017-12-01', 'month', 7637.3, 'completed', 'REPORTED', 'S006') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-LT', 'Consortium member', NULL::numeric, 'Larsen & Toubro Limited', 'REPORTED'::itis.confidence_level, 'S006'), ('C-IHI', 'Consortium member', NULL::numeric, 'IHI Corporation', 'REPORTED'::itis.confidence_level, 'S006')) AS v;
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0003', 'Pkg 2', 'Navi Mumbai side marine viaduct', 7.807, NULL, NULL, 'CROSS_VERIFIED', 'S007');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0003' AND package_no='Pkg 2'), 'Unknown', '2017-12-01', 'month', 5612.61, 'completed', 'CROSS_VERIFIED', 'S007') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-DAEWOO', 'JV member', NULL::numeric, 'Daewoo Engineering & Construction', 'CROSS_VERIFIED'::itis.confidence_level, 'S007'), ('C-TPL', 'JV member', NULL::numeric, 'Tata Projects Limited', 'CROSS_VERIFIED'::itis.confidence_level, 'S007')) AS v;
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0003', 'Pkg 3', 'Land viaduct towards Chirle', 3.613, NULL, NULL, 'REPORTED', 'S006');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0003' AND package_no='Pkg 3'), 'Unknown', '2017-12-01', 'month', 1013.79, 'completed', 'REPORTED', 'S006') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-LT', 'Sole contractor', NULL::numeric, 'Larsen & Toubro Limited', 'REPORTED'::itis.confidence_level, 'S006')) AS v;
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0003', 17843, 'reported_cost', 'Construction cost', NULL, 'unknown', true, 'Most specific whole-project cost reported', NULL, 'REPORTED', 'S006');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0003', '2017-12-01', 'month', 'award', 'AWARDED', 'Civil packages 1–3 contracts signed', 'REPORTED', 'S006'),
  ('ITI-P-0003', '2024-01-01', 'month', 'opening', 'OPEN_TO_TRAFFIC', 'Bridge opened to traffic', 'REPORTED', 'S006');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0003', '2024-01-01', 'month', 100, 'Open to traffic since January 2024 (S006)', 'S006');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0003', 'schematic', ST_GeomFromText('LINESTRING(72.857 19, 72.93 18.97, 72.99 18.92)', 4326), 'APPROXIMATE', 'Landmark endpoints', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0003', 'Tolling / ITS', 'potential', 'Tolled sea bridge'),
  ('ITI-P-0003', 'CCTV / surveillance', 'potential', 'Long marine structure');

-- ITI-P-0004 Zojila Tunnel
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0004', 'Zojila Tunnel', 'Tunnel', 'Mountain / strategic road tunnel', 'CR-SRINAGAR-LEH', 'NH-1', 'MoRTH (NHIDCL)', 'Baltal (J&K)', 'Minamarg (Kargil, Ladakh)', 30.18, '13.153 km tunnel + 17.03 km approach roads (S009)', '2 (single-tube bi-directional)', 'High-altitude mountain', 'Strategic all-weather link to Ladakh', 'A-MORTH', 'A-NHIDCL', 'REPORTED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0004', 'Zojila Tunnel', 'zojila tunnel'),
  ('ITI-P-0004', 'Zoji-la Tunnel', 'zoji la tunnel'),
  ('ITI-P-0004', 'Zojila Pass Tunnel', 'zojila pass tunnel');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0004', 'IN-JK', false),
  ('ITI-P-0004', 'IN-LA', true);
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0004', 'EPC', 'Zojila tunnel + approaches', 30.18, NULL, NULL, 'REPORTED', 'S009');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0004' AND package_no='EPC'), 'Unknown', '2020-01-01', 'year', NULL, 'active', 'REPORTED', 'S009') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-MEIL', 'Sole contractor', NULL::numeric, 'Megha Engineering & Infrastructures Ltd', 'REPORTED'::itis.confidence_level, 'S009')) AS v;
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0004', 6809.69, 'reported_cost', 'Total project cost', NULL, 'unknown', true, 'Most specific whole-project cost reported', NULL, 'REPORTED', 'S042');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0004', '2020-01-01', 'year', 're_tender', 'RE_TENDERED', 'Re-awarded to MEIL after previous contractor (IL&FS) exited', 'REPORTED', 'S009'),
  ('ITI-P-0004', '2026-05-01', 'month', 'milestone', NULL, 'Milestone: <1 km of excavation remaining', 'REPORTED', 'S043'),
  ('ITI-P-0004', '2026-06-09', 'day', 'milestone', NULL, 'Milestone: final breakthrough blast reported', 'REPORTED', 'S010'),
  ('ITI-P-0004', '2026-01-01', 'year', 'delay', 'DELAYED', 'Completion pushed to Feb 2028 with cost escalation', 'REPORTED', 'S008');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0004', '2026-06-01', 'month', NULL, '~12 km of 13.153 km excavated by mid-May 2026 (S043); final breakthrough blast reported 9 Jun 2026 (S010 — tier 4, needs primary confirmation)', 'S008');
INSERT INTO delay_risks (project_id, category, description, source_id) VALUES
  ('ITI-P-0004', 'Contractor financial stress', 'Original contractor IL&FS exited; project re-awarded in 2020', 'S009'),
  ('ITI-P-0004', 'Other', 'Delay and cost escalation reported; completion revised to 2028', 'S008');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0004', 'schematic', ST_GeomFromText('LINESTRING(75.41 34.25, 75.47 34.3, 75.53 34.33)', 4326), 'APPROXIMATE', 'Named portal localities', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0004', 'Tunnel management (ventilation/SCADA/fire/CCTV/comms)', 'potential', '13 km high-altitude road tunnel');
INSERT INTO opportunity_signals (project_id, category, signal_type, signal_date, description, source_id, last_verified) VALUES
  ('ITI-P-0004', 'CONSTRUCTION', 'Construction milestone', '2026-05-01', 'Excavation near complete (2026); tunnel E&M/systems phase would follow', 'S043', '2026-09-28');

-- ITI-P-0005 Bengaluru–Chennai Expressway
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0005', 'Bengaluru–Chennai Expressway', 'Expressway', 'Greenfield access-controlled expressway', 'CR-BENGALURU-CHENNAI', 'NE-7', 'Bharatmala Pariyojana', 'Hoskote', 'Sriperumbudur', 262.9, 'Karnataka 71.7 + AP 85.2 + TN 106 km (S011)', '4 (per S013)', 'Plain / plateau', 'Inter-metro corridor', 'A-MORTH', 'A-NHAI', 'REPORTED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0005', 'Bengaluru–Chennai Expressway', 'bengaluru chennai expressway'),
  ('ITI-P-0005', 'Bangalore Chennai Expressway', 'bangalore chennai expressway'),
  ('ITI-P-0005', 'NE-7', 'ne 7');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0005', 'IN-KA', false),
  ('ITI-P-0005', 'IN-AP', false),
  ('ITI-P-0005', 'IN-TN', true);
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0005', 7811, 'estimated', 'Cost of identified stretches at start (2022)', '2022-01-01', 'year', false, NULL, 'Two reported values reflect initial (2022) vs revised (Mar-2026) cost of the same identified stretches — not independent estimates. Neither is the full-corridor cost.', 'REPORTED', 'S011'),
  ('ITI-P-0005', 10507, 'revised', 'Cost of identified stretches (revised)', '2026-03-01', 'month', true, 'Most specific whole-project cost reported', NULL, 'REPORTED', 'S011');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0005', '2024-01-01', 'year', 'delay', 'DELAYED', 'Original late-2024 target missed', 'REPORTED', 'S011'),
  ('ITI-P-0005', '2025-08-01', 'month', 'delay', 'DELAYED', 'Revised Aug-2025 target missed', 'REPORTED', 'S011'),
  ('ITI-P-0005', '2026-01-01', 'year', 'delay', 'DELAYED', 'Third deadline set to be missed; completion expected 2027', 'REPORTED', 'S011');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0005', '2026-01-01', 'year', NULL, '>230 km completed; end-to-end expected 2027 (S011)', 'S011');
INSERT INTO delay_risks (project_id, category, description, source_id) VALUES
  ('ITI-P-0005', 'Land acquisition', 'Land acquisition delays', 'S011'),
  ('ITI-P-0005', 'Utility shifting', 'Utility shifting issues', 'S011'),
  ('ITI-P-0005', 'Litigation', 'Arakkonam–Kancheepuram package under court case', 'S011'),
  ('ITI-P-0005', 'Contractor performance', 'Contractor performance problems cited', 'S011');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0005', 'schematic', ST_GeomFromText('LINESTRING(77.8 13.07, 78.18 12.99, 78.75 13.2, 79.67 13.08, 79.95 12.97)', 4326), 'APPROXIMATE', 'Town-to-town schematic', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0005', 'Tolling / ITS', 'potential', 'Access-controlled expressway');
INSERT INTO opportunity_signals (project_id, category, signal_type, signal_date, description, source_id, last_verified) VALUES
  ('ITI-P-0005', 'CONSTRUCTION', 'Construction milestone', '2026-01-01', 'Remaining stretches under construction; litigated package pending', 'S011', '2026-09-28');

-- ITI-P-0006 Mumbai Coastal Road (South) — Marine Drive to Worli
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0006', 'Mumbai Coastal Road (South) — Marine Drive to Worli', 'Urban road', 'Urban coastal expressway with tunnels & interchanges', 'CR-MUMBAI-COASTAL-ROAD', NULL, 'Municipal (BMC)', 'Marine Drive (Princess Street)', 'Worli (Bandra–Worli Sea Link)', 10.58, '10.58 km corridor (S014)', '8 (per S014)', 'Urban coastal / reclaimed', 'Metropolitan arterial', NULL, 'A-BMC', 'REPORTED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0006', 'Mumbai Coastal Road (South) — Marine Drive to Worli', 'mumbai coastal road south marine drive to worli'),
  ('ITI-P-0006', 'Dharmaveer Swarajya Rakshak Chhatrapati Sambhaji Maharaj Coastal Road', 'dharmaveer swarajya rakshak chhatrapati sambhaji maharaj coastal road'),
  ('ITI-P-0006', 'MCRP', 'mcrp'),
  ('ITI-P-0006', 'Coastal Road Phase 1', 'coastal road phase 1');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0006', 'IN-MH', true);
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0006', 'Pkg 1 & 4', 'Princess Street–Priyadarshini Park; Baroda Palace–BWSL (combined award)', NULL, NULL, NULL, 'REPORTED', 'S014');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0006' AND package_no='Pkg 1 & 4'), 'Unknown', NULL, 'unknown', 7489, 'completed', 'REPORTED', 'S014') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-LT', 'Sole contractor', NULL::numeric, 'Larsen & Toubro Limited', 'REPORTED'::itis.confidence_level, 'S014')) AS v;
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0006', 'Pkg 2', 'Priyadarshini Park–Baroda Palace', NULL, NULL, NULL, 'REPORTED', 'S014');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0006' AND package_no='Pkg 2'), 'Unknown', NULL, 'unknown', 2126, 'completed', 'REPORTED', 'S014') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-HCC', 'JV lead', 55, 'Hindustan Construction Company Ltd', 'REPORTED'::itis.confidence_level, 'S014'), ('C-HDC', 'JV member', 45, 'Hyundai Development Company', 'REPORTED'::itis.confidence_level, 'S014')) AS v;
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0006', 13060, 'estimated', 'Estimated project cost', NULL, 'unknown', true, 'Most specific whole-project cost reported', NULL, 'REPORTED', 'S014'),
  ('ITI-P-0006', 339.32, 'cost_variation', 'Cost increase (variation)', NULL, 'unknown', false, NULL, NULL, 'REPORTED', 'S015');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0006', '2024-03-11', 'day', 'opening', 'PARTIALLY_OPERATIONAL', 'Phase-1 south-bound arm (9.5 of 10.58 km) inaugurated', 'REPORTED', 'S014'),
  ('ITI-P-0006', '2025-01-26', 'day', 'opening', 'PARTIALLY_OPERATIONAL', 'Northbound bridge to Bandra–Worli Sea Link inaugurated', 'REPORTED', 'S016'),
  ('ITI-P-0006', '2025-08-15', 'day', 'opening', 'OPERATIONAL', '24x7 operation and promenade opening reported', 'REPORTED', 'S016');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0006', '2025-08-01', 'month', NULL, 'Northbound BWSL connector opened 26 Jan 2025 (S016); 24x7 operation from 15 Aug 2025 (search summary; needs primary confirmation)', 'S016');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0006', 'schematic', ST_GeomFromText('LINESTRING(72.822 18.945, 72.806 18.965, 72.81 18.982, 72.815 19.01)', 4326), 'APPROXIMATE', 'Landmark endpoints', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0006', 'Tunnel management / traffic control centre', 'potential', 'Urban twin tunnels on corridor (S014)');

-- ITI-P-0007 Ganga Expressway
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0007', 'Ganga Expressway', 'Expressway', 'Greenfield access-controlled expressway', 'CR-MEERUT-PRAYAGRAJ', NULL, 'State (Uttar Pradesh)', 'Meerut', 'Prayagraj', 594, '594 km (S017, S018)', '6', 'Plain (Gangetic)', 'State economic corridor', NULL, 'A-UPEIDA', 'CROSS_VERIFIED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0007', 'Ganga Expressway', 'ganga expressway'),
  ('ITI-P-0007', 'Meerut–Prayagraj Expressway', 'meerut prayagraj expressway');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0007', 'IN-UP', true);
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0007', 'Group 1', 'Meerut–Badaun section', 129.7, NULL, NULL, 'REPORTED', 'S019');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0007' AND package_no='Group 1'), 'Unknown', NULL, 'unknown', 5039, 'completed', 'REPORTED', 'S019') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-IRB', 'Sole contractor', NULL::numeric, 'IRB Infrastructure Developers Ltd', 'REPORTED'::itis.confidence_level, 'S019')) AS v;
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0007', 'Groups 2–4', 'Badaun–Prayagraj (~80% of route)', NULL, NULL, NULL, 'REPORTED', 'S019');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0007' AND package_no='Groups 2–4'), 'Unknown', NULL, 'unknown', NULL, 'completed', 'REPORTED', 'S019') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-ADANI', 'Sole contractor', NULL::numeric, 'Adani Enterprises Ltd', 'REPORTED'::itis.confidence_level, 'S019')) AS v;
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0007', 36230, 'reported_cost', 'Project cost', NULL, 'unknown', true, 'Most specific whole-project cost reported', '₹36,000 cr is a rounded headline figure; ₹36,230 cr is the project cost reported at award. Consistent, not conflicting.', 'REPORTED', 'S019'),
  ('ITI-P-0007', 36000, 'headline', 'Headline cost (''more than ₹36,000 cr'')', '2026-04-29', 'day', false, NULL, NULL, 'REPORTED', 'S018');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0007', '2026-04-29', 'day', 'opening', 'OPEN_TO_TRAFFIC', 'Inaugurated by PM at Hardoi; opened with tolling', 'REPORTED', 'S018');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0007', '2026-04-29', 'day', NULL, 'Inaugurated 29 Apr 2026 at Hardoi; tolling began (S044)', 'S018');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0007', 'schematic', ST_GeomFromText('LINESTRING(77.71 28.98, 79.12 28.03, 79.91 27.88, 80.13 27.4, 80.49 26.55, 81.23 26.23, 81.95 25.52)', 4326), 'APPROXIMATE', 'Town-to-town schematic', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0007', 'Tolling / ATMS', 'potential', 'Tolled access-controlled expressway, newly operational');

-- ITI-P-0008 Sela Tunnel
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0008', 'Sela Tunnel', 'Tunnel', 'Strategic mountain road tunnel', 'CR-BALIPARA-CHARIDUAR-TAWANG', NULL, 'BRO — Project Vartak', 'West Kameng', 'Tawang', 11.315, 'Tunnels 0.98 + 1.555 km + 8.78 km approach roads (S020)', '2', 'High-altitude mountain (~13,000 ft)', 'Strategic border connectivity', NULL, 'A-BRO', 'VERIFIED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0008', 'Sela Tunnel', 'sela tunnel'),
  ('ITI-P-0008', 'Sela Pass Tunnel', 'sela pass tunnel');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0008', 'IN-AR', true);
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0008', 'Main', 'Twin tunnels + approach roads', 11.315, NULL, NULL, 'REPORTED', 'S021');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0008' AND package_no='Main'), 'Unknown', NULL, 'unknown', NULL, 'completed', 'REPORTED', 'S021') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-PATEL', 'Sole contractor', NULL::numeric, 'Patel Engineering Ltd', 'REPORTED'::itis.confidence_level, 'S021')) AS v;
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0008', 825, 'reported_cost', 'Total cost', '2024-03-09', 'day', true, 'Most specific whole-project cost reported', NULL, 'VERIFIED', 'S020');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0008', '2024-03-09', 'day', 'opening', 'OPERATIONAL', 'Dedicated to the nation by PM (virtually, from Itanagar)', 'REPORTED', 'S020');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0008', '2024-03-09', 'day', 100, 'Dedicated to the nation 9 Mar 2024', 'S020');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0008', 'centroid', ST_GeomFromText('POINT(92.1 27.5)', 4326), 'APPROXIMATE', 'Sela Pass locality', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0008', 'Tunnel systems', 'potential', 'Road tunnel >1 km');

-- ITI-P-0009 Dwarka Expressway
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0009', 'Dwarka Expressway', 'Expressway', 'Urban elevated expressway', 'CR-DELHI-GURUGRAM', 'NH-248BB', 'Bharatmala Pariyojana', 'Shiv Murti / Mahipalpur (Delhi)', 'Kherki Daula (Gurugram)', 29.1, 'Delhi 10.1 km (S022) + Haryana ~19 km (S024)', '8', 'Urban', 'NCR decongestion', 'A-MORTH', 'A-NHAI', 'CROSS_VERIFIED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0009', 'Dwarka Expressway', 'dwarka expressway'),
  ('ITI-P-0009', 'Northern Peripheral Road', 'northern peripheral road'),
  ('ITI-P-0009', 'NH-248BB', 'nh 248bb');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0009', 'IN-DL', false),
  ('ITI-P-0009', 'IN-HR', true);
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0009', 'Pkg 1', 'Delhi section (Shiv Murti–Dwarka Sec 21)', NULL, NULL, NULL, 'REPORTED', 'S049');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0009' AND package_no='Pkg 1'), 'Unknown', NULL, 'unknown', 1349, 'completed', 'REPORTED', 'S049') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-JKUMAR', 'Sole contractor', NULL::numeric, 'J. Kumar Infraprojects Ltd', 'REPORTED'::itis.confidence_level, 'S049')) AS v;
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0009', 'Pkg 4', 'Basai ROB–Kherki Daula (8.76 km)', 8.76, NULL, NULL, 'REPORTED', 'S023');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0009' AND package_no='Pkg 4'), 'Unknown', NULL, 'unknown', 1047, 'completed', 'REPORTED', 'S023') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-LT', 'Sole contractor', NULL::numeric, 'Larsen & Toubro Limited', 'REPORTED'::itis.confidence_level, 'S023')) AS v;
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0009', 5360, 'reported_cost', 'Delhi section cost', '2025-08-01', 'month', false, NULL, NULL, 'VERIFIED', 'S022'),
  ('ITI-P-0009', 4100, 'reported_cost', 'Haryana section cost (approx.)', '2024-03-11', 'day', false, NULL, NULL, 'REPORTED', 'S024'),
  ('ITI-P-0009', 9460, 'computed_sum', 'Computed: Delhi + Haryana section costs (sum of two reported values)', '2025-08-01', 'month', true, 'No whole-project figure reported; sum of section costs', NULL, 'INFERRED', 'S022');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0009', '2024-03-11', 'day', 'opening', 'PARTIALLY_OPERATIONAL', 'Haryana section (~19 km) inaugurated', 'REPORTED', 'S024'),
  ('ITI-P-0009', '2025-08-17', 'day', 'opening', 'OPERATIONAL', 'Delhi section (10.1 km, incl. 5.1 km tunnel to IGI Airport) inaugurated', 'REPORTED', 'S046');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0009', '2025-08-17', 'day', NULL, 'Haryana section opened 11 Mar 2024; Delhi section opened 17 Aug 2025', 'S046');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0009', 'schematic', ST_GeomFromText('LINESTRING(77.13 28.54, 77.06 28.55, 77.02 28.49, 76.98 28.4)', 4326), 'APPROXIMATE', 'Landmark endpoints', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0009', 'Urban tunnel systems / ATMS', 'potential', '5.1 km urban tunnel section (S022)');

-- ITI-P-0010 Z-Morh (Sonamarg) Tunnel
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0010', 'Z-Morh (Sonamarg) Tunnel', 'Tunnel', 'Strategic mountain road tunnel', 'CR-SRINAGAR-LEH', 'NH-1', 'MoRTH (NHIDCL)', 'Gagangir', 'Sonamarg', 6.5, '6.5 km (S027)', '2', 'Mountain', 'All-weather access to Sonamarg; with Zojila, to Ladakh', 'A-MORTH', 'A-NHIDCL', 'CROSS_VERIFIED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0010', 'Z-Morh (Sonamarg) Tunnel', 'z morh sonamarg tunnel'),
  ('ITI-P-0010', 'Sonamarg Tunnel', 'sonamarg tunnel'),
  ('ITI-P-0010', 'Z-Morh Tunnel', 'z morh tunnel');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0010', 'IN-JK', true);
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0010', 'EPC', 'Z-Morh tunnel', 6.5, NULL, NULL, 'REPORTED', 'S027');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0010' AND package_no='EPC'), 'Unknown', NULL, 'unknown', 2680, 'completed', 'REPORTED', 'S027') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-APCO', 'Sole contractor', NULL::numeric, 'APCO Infratech Pvt Ltd', 'REPORTED'::itis.confidence_level, 'S027')) AS v;
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0010', 2700, 'headline', 'Project cost (headline)', '2025-01-13', 'day', true, 'Most specific whole-project cost reported', '₹2,700 cr (project, headline) vs ₹2,680 cr (contract award). Likely project vs contract value — different value types.', 'REPORTED', 'S026'),
  ('ITI-P-0010', 2680, 'award', 'Contract value after re-tender', NULL, 'unknown', false, NULL, NULL, 'REPORTED', 'S027');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0010', NULL, 'unknown', 're_tender', 'RE_TENDERED', 'Project re-tendered before award to APCO Infratech', 'REPORTED', 'S027'),
  ('ITI-P-0010', '2025-01-13', 'day', 'opening', 'OPERATIONAL', 'Inaugurated by PM', 'REPORTED', 'S026');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0010', '2025-01-13', 'day', 100, 'Inaugurated 13 Jan 2025', 'S026');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0010', 'schematic', ST_GeomFromText('LINESTRING(75.2 34.29, 75.29 34.3)', 4326), 'APPROXIMATE', 'Named portal localities', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0010', 'Tunnel systems', 'potential', '6.5 km road tunnel');

-- ITI-P-0011 Thane–Borivali Twin Tube Road Tunnel
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0011', 'Thane–Borivali Twin Tube Road Tunnel', 'Tunnel', 'Urban twin-tube road tunnel (TBM)', 'CR-THANE-BORIVALI', NULL, 'MMRDA', 'Thane (Manpada)', 'Borivali', 11.84, '11.84 km (S029 via search)', '3 per tube (reported)', 'Urban / under national park', 'Metropolitan link', NULL, 'A-MMRDA', 'REPORTED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0011', 'Thane–Borivali Twin Tube Road Tunnel', 'thane borivali twin tube road tunnel'),
  ('ITI-P-0011', 'Thane Borivali Tunnel', 'thane borivali tunnel'),
  ('ITI-P-0011', 'TBT', 'tbt');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0011', 'IN-MH', true);
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0011', 'Pkg 1', 'Twin tunnel package 1', NULL, NULL, NULL, 'CROSS_VERIFIED', 'S028');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0011' AND package_no='Pkg 1'), 'Unknown', NULL, 'unknown', 7464, 'active', 'CROSS_VERIFIED', 'S028') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-MEIL', 'Sole contractor', NULL::numeric, 'Megha Engineering & Infrastructures Ltd', 'CROSS_VERIFIED'::itis.confidence_level, 'S028')) AS v;
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0011', 'Pkg 2', 'Twin tunnel package 2', NULL, NULL, NULL, 'CROSS_VERIFIED', 'S028');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0011' AND package_no='Pkg 2'), 'Unknown', NULL, 'unknown', 6937, 'active', 'CROSS_VERIFIED', 'S028') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-MEIL', 'Sole contractor', NULL::numeric, 'Megha Engineering & Infrastructures Ltd', 'CROSS_VERIFIED'::itis.confidence_level, 'S028')) AS v;
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0011', 14401, 'award', 'Combined award value (Pkg 1 + Pkg 2)', NULL, 'unknown', true, 'Most specific whole-project cost reported', NULL, 'REPORTED', 'S028');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0011', '2025-08-01', 'month', 'status_change', 'UNDER_CONSTRUCTION', '>8% physical progress', 'REPORTED', 'S029'),
  ('ITI-P-0011', '2026-05-29', 'day', 'status_change', 'UNDER_CONSTRUCTION', 'TBM-03 factory acceptance test completed at Chennai', 'REPORTED', 'S029');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0011', '2025-08-01', 'month', 8, '>8% progress as of Aug 2025; TBM-03 factory acceptance completed 29 May 2026 (S029)', 'S029');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0011', 'schematic', ST_GeomFromText('LINESTRING(72.975 19.235, 72.92 19.232, 72.865 19.23)', 4326), 'APPROXIMATE', 'Endpoint localities', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0011', 'Tunnel management (ventilation/SCADA/fire/CCTV/comms)', 'potential', '11.8 km urban twin-tube road tunnel'),
  ('ITI-P-0011', 'Control room / data centre', 'potential', 'Urban tunnel O&M');
INSERT INTO opportunity_signals (project_id, category, signal_type, signal_date, description, source_id, last_verified) VALUES
  ('ITI-P-0011', 'CONSTRUCTION', 'Construction milestone', '2026-05-29', 'TBM boring phase starting; E&M/systems packages would follow civil works', 'S029', '2026-09-28');

-- ITI-P-0012 Pune Outer Ring Road
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0012', 'Pune Outer Ring Road', 'Ring road', 'Greenfield ring road', 'CR-PUNE-RING-ROAD', NULL, 'State (Maharashtra)', 'Pune (western arc)', 'Pune (eastern arc)', NULL, 'Total length not captured from a cited source; western packages W1–W5 sum to 65.45 km (computed from S031)', NULL, 'Plateau / hilly', 'Metropolitan bypass', NULL, 'A-MSRDC', 'REPORTED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0012', 'Pune Outer Ring Road', 'pune outer ring road'),
  ('ITI-P-0012', 'Pune Ring Road', 'pune ring road'),
  ('ITI-P-0012', 'PRR', 'prr');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0012', 'IN-MH', true);
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0012', 'PRR-W1', 'Western package 1', 14.65, 19, '2026-01-19', 'REPORTED', 'S031');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0012' AND package_no='PRR-W1'), 'Unknown', '2024-01-01', 'year', NULL, 'active', 'REPORTED', 'S031') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-MEIL', 'Sole contractor', NULL::numeric, 'Megha Engineering & Infrastructures Ltd', 'REPORTED'::itis.confidence_level, 'S031')) AS v;
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0012', 'PRR-W2', 'Western package 2', 20, 31, '2026-01-19', 'REPORTED', 'S031');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0012' AND package_no='PRR-W2'), 'Unknown', '2024-01-01', 'year', NULL, 'active', 'REPORTED', 'S031') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-NECL', 'Sole contractor', NULL::numeric, 'Navayuga Engineering Company Ltd', 'REPORTED'::itis.confidence_level, 'S031')) AS v;
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0012', 'PRR-W3', 'Western package 3', 14, 36, '2026-01-19', 'REPORTED', 'S031');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0012' AND package_no='PRR-W3'), 'Unknown', '2024-01-01', 'year', NULL, 'active', 'REPORTED', 'S031') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-NECL', 'Sole contractor', NULL::numeric, 'Navayuga Engineering Company Ltd', 'REPORTED'::itis.confidence_level, 'S031')) AS v;
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0012', 'PRR-W4', 'Western package 4', 7.5, 35, '2026-01-19', 'REPORTED', 'S031');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0012' AND package_no='PRR-W4'), 'Unknown', '2024-01-01', 'year', NULL, 'active', 'REPORTED', 'S031') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-NECL', 'Sole contractor', NULL::numeric, 'Navayuga Engineering Company Ltd', 'REPORTED'::itis.confidence_level, 'S031')) AS v;
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0012', 'PRR-W5', 'Western package 5', 9.3, 25, '2026-01-19', 'REPORTED', 'S031');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0012' AND package_no='PRR-W5'), 'Unknown', '2024-01-01', 'year', NULL, 'active', 'REPORTED', 'S031') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-GRIL', 'Sole contractor', NULL::numeric, 'G R Infraprojects Ltd', 'REPORTED'::itis.confidence_level, 'S031')) AS v;
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0012', 'PRR-E5', 'Eastern package 5', NULL, NULL, NULL, 'REPORTED', 'S047');
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0012', 'PRR-E6', 'Eastern package 6', NULL, NULL, NULL, 'REPORTED', 'S047');
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0012', 'PRR-E7', 'Eastern package 7', NULL, NULL, NULL, 'REPORTED', 'S047');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0012', '2024-01-01', 'year', 'award', 'AWARDED', '9 of 12 packages awarded to MEIL, Navayuga, GR Infra, PNC, RSIIL', 'REPORTED', 'S032'),
  ('ITI-P-0012', '2025-01-01', 'month', 'tender', 'BID_EVALUATION', 'Financial bids for E5–E7 opened; above estimates', 'REPORTED', 'S047'),
  ('ITI-P-0012', '2026-01-19', 'day', 'status_change', 'PACKAGE_WISE_CONSTRUCTION', 'Western packages at 19–36% progress', 'REPORTED', 'S031');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0012', '2026-01-19', 'day', NULL, '9 of 12 packages under construction; E5–E7 not awarded (S031, S047)', 'S031');
INSERT INTO delay_risks (project_id, category, description, source_id) VALUES
  ('ITI-P-0012', 'Funding issues', 'E5–E7 bids significantly above MSRDC estimates; award pending', 'S047');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0012', 'centroid', ST_GeomFromText('POINT(73.86 18.52)', 4326), 'APPROXIMATE', 'City centroid only — alignment not ingested', false);
INSERT INTO opportunity_signals (project_id, category, signal_type, signal_date, description, source_id, last_verified) VALUES
  ('ITI-P-0012', 'RE_TENDER', 'Other', '2025-12-01', 'E5–E7 bids above estimate, under negotiation; could be awarded or re-tendered', 'S047', '2026-09-28');

-- ITI-P-0013 Atal Tunnel (Rohtang)
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0013', 'Atal Tunnel (Rohtang)', 'Tunnel', 'Strategic high-altitude road tunnel', 'CR-MANALI-LEH', NULL, 'BRO', 'Manali side (south portal)', 'Lahaul (north portal)', 9.02, '9.02 km (S033)', '2', 'High-altitude mountain', 'Strategic all-weather link', NULL, 'A-BRO', 'VERIFIED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0013', 'Atal Tunnel (Rohtang)', 'atal tunnel rohtang'),
  ('ITI-P-0013', 'Rohtang Tunnel', 'rohtang tunnel'),
  ('ITI-P-0013', 'Atal Tunnel', 'atal tunnel');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0013', 'IN-HP', true);
INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES ('ITI-P-0013', 'Main', 'Atal Tunnel', 9.02, NULL, NULL, 'REPORTED', 'S033');
WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES ((SELECT package_id FROM packages WHERE project_id='ITI-P-0013' AND package_no='Main'), 'Unknown', NULL, 'unknown', NULL, 'completed', 'REPORTED', 'S033') RETURNING contract_id)
INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ('C-STRABAG', 'JV member', NULL::numeric, 'STRABAG', 'REPORTED'::itis.confidence_level, 'S033'), ('C-AFCONS', 'JV member', NULL::numeric, 'Afcons Infrastructure Ltd', 'REPORTED'::itis.confidence_level, 'S033')) AS v;
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0013', 3200, 'reported_cost', 'Reported cost', NULL, 'unknown', true, 'Most specific whole-project cost reported', NULL, 'REPORTED', 'S033');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0013', '2010-06-28', 'day', 'status_change', 'UNDER_CONSTRUCTION', 'Construction commenced', 'REPORTED', 'S033'),
  ('ITI-P-0013', '2020-10-03', 'day', 'opening', 'OPERATIONAL', 'Inaugurated by PM', 'REPORTED', 'S034');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0013', '2020-10-03', 'day', 100, 'Inaugurated 3 Oct 2020', 'S034');
INSERT INTO delay_risks (project_id, category, description, source_id) VALUES
  ('ITI-P-0013', 'Geological conditions', 'Water ingress and geological faults during construction', 'S033');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0013', 'schematic', ST_GeomFromText('LINESTRING(77.17 32.36, 77.15 32.4, 77.13 32.44)', 4326), 'APPROXIMATE', 'Portal localities', false);

-- ITI-P-0014 Delhi–Amritsar–Katra Expressway
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0014', 'Delhi–Amritsar–Katra Expressway', 'Expressway', 'Greenfield access-controlled expressway', 'CR-DELHI-AMRITSAR-KATRA', 'NE-5', 'Bharatmala Pariyojana', 'Bahadurgarh (KMP)', 'Katra', 670, '~669–670 km (S035)', '4 (expandable to 8) per S035', 'Plain / sub-Himalayan', 'National economic & strategic corridor', 'A-MORTH', 'A-NHAI', 'REPORTED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0014', 'Delhi–Amritsar–Katra Expressway', 'delhi amritsar katra expressway'),
  ('ITI-P-0014', 'DAK Expressway', 'dak expressway'),
  ('ITI-P-0014', 'Delhi Katra Expressway', 'delhi katra expressway'),
  ('ITI-P-0014', 'NE-5', 'ne 5');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0014', 'IN-DL', false),
  ('ITI-P-0014', 'IN-HR', false),
  ('ITI-P-0014', 'IN-PB', true),
  ('ITI-P-0014', 'IN-JK', false);
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0014', 39500, 'reported_cost', 'Announced project cost (2022)', '2022-01-01', 'year', true, 'Most specific whole-project cost reported', NULL, 'REPORTED', 'S035');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0014', '2024-11-01', 'month', 'opening', 'PARTIALLY_OPERATIONAL', '135 km Haryana section operational', 'REPORTED', 'S035'),
  ('ITI-P-0014', NULL, 'unknown', 'cancellation', 'CANCELLED', 'Tender for ~30 km Amritsar-spur section cancelled — land not acquired', 'REPORTED', 'S036'),
  ('ITI-P-0014', '2026-07-17', 'day', 'opening', 'PARTIALLY_OPERATIONAL', 'Further Punjab stretches inaugurated (reported)', 'REPORTED', 'S035');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0014', '2026-07-01', 'month', NULL, 'Haryana 135 km operational since Nov-2024; further Punjab packages opened Jul-2026 (S035 — needs primary confirmation)', 'S037');
INSERT INTO delay_risks (project_id, category, description, source_id) VALUES
  ('ITI-P-0014', 'Land acquisition', 'Land acquisition hurdles in Punjab; spur tender cancelled', 'S036'),
  ('ITI-P-0014', 'Weather', 'Monsoon flooding in J&K sector cited', 'S037');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0014', 'schematic', ST_GeomFromText('LINESTRING(76.92 28.69, 76.31 29.32, 76.4 29.8, 75.84 30.25, 75.47 31.13, 75.4 32.04, 75.52 32.37, 74.93 32.99)', 4326), 'APPROXIMATE', 'Town-to-town schematic', false);
INSERT INTO technology_requirements (project_id, domain, kind, basis) VALUES
  ('ITI-P-0014', 'Tolling / ITS', 'potential', 'Access-controlled expressway');
INSERT INTO opportunity_signals (project_id, category, signal_type, signal_date, description, source_id, last_verified) VALUES
  ('ITI-P-0014', 'RE_TENDER', 'Tender cancellation', '2026-01-01', 'Amritsar-spur section tender cancelled over land; returns to procurement only once land is acquired', 'S036', '2026-09-28');

-- ITI-P-0015 Shaktipeeth Expressway
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0015', 'Shaktipeeth Expressway', 'Expressway', 'Greenfield access-controlled expressway (planned)', 'CR-NAGPUR-GOA', NULL, 'State (Maharashtra)', 'Pavnar (Wardha)', 'Patradevi (Maharashtra–Goa border)', 803, '~803 km original; ~857 km revised alignment (S040 — tier 4)', NULL, 'Mixed', 'State corridor (pilgrimage/economic)', NULL, 'A-MSRDC', 'REPORTED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0015', 'Shaktipeeth Expressway', 'shaktipeeth expressway'),
  ('ITI-P-0015', 'Nagpur–Goa Expressway', 'nagpur goa expressway'),
  ('ITI-P-0015', 'Maharashtra Shaktipeeth Mahamarg', 'maharashtra shaktipeeth mahamarg');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0015', 'IN-MH', true),
  ('ITI-P-0015', 'IN-GA', false);
INSERT INTO project_values (project_id, value_cr, value_type, value_type_detail, as_of_date, as_of_precision, is_reference, reference_reason, discrepancy_note, record_confidence, source_id) VALUES
  ('ITI-P-0015', 86300, 'estimated', 'Estimated project cost', NULL, 'unknown', false, NULL, 'Multiple publicly reported values exist; value requires further verification. ₹20,787 cr appears to be an allocation/budget line (incl. land), not the total project cost.', 'REPORTED', 'S038'),
  ('ITI-P-0015', 20787, 'budget_allocation', 'Budget (of which ₹12,000 cr for land acquisition)', NULL, 'unknown', false, NULL, NULL, 'REPORTED', 'S038');
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0015', '2022-10-01', 'month', 'tender', 'TENDER_ISSUED', 'EPC tenders reported launched by MSRDC (tier 4 claim — needs primary verification)', 'REPORTED', 'S038'),
  ('ITI-P-0015', '2025-06-24', 'day', 'approval', 'APPROVED', 'Approved by Maharashtra Cabinet', 'REPORTED', 'S038'),
  ('ITI-P-0015', '2026-01-01', 'year', 'status_change', 'LAND_ACQUISITION', 'Revised alignment (~857 km) approved; LA & clearances in progress', 'REPORTED', 'S040');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0015', '2026-01-01', 'year', 0, 'Revised alignment approved 2026; DPR finalisation, clearances, land acquisition in progress (S040)', 'S040');
INSERT INTO delay_risks (project_id, category, description, source_id) VALUES
  ('ITI-P-0015', 'Local opposition', 'Project was shelved and later revived (S039); drivers not captured in detail', 'S039');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0015', 'schematic', ST_GeomFromText('LINESTRING(78.67 20.78, 77.32 19.14, 76.57 18.4, 75.9 17.66, 74.24 16.7, 73.8 15.72)', 4326), 'APPROXIMATE', 'Planned — schematic between reported endpoints; not an alignment', true);
INSERT INTO opportunity_signals (project_id, category, signal_type, signal_date, description, source_id, last_verified) VALUES
  ('ITI-P-0015', 'TENDER_EXPECTED', 'Cabinet approval', '2026-01-01', 'Cabinet approval (24 Jun 2025) + revised alignment approval (2026); LA in progress. No dated tender notice captured.', 'S038', '2026-09-28');

-- ITI-P-0016 Vadhavan Port–Samruddhi Expressway Freight Corridor
INSERT INTO projects (project_id, canonical_name, project_type, category, corridor_id, highway_no, programme, origin, destination, length_km, length_basis, lanes, terrain, strategic_importance, nodal_ministry_id, implementing_authority_id, record_confidence, last_verified) VALUES
  ('ITI-P-0016', 'Vadhavan Port–Samruddhi Expressway Freight Corridor', 'Expressway', 'Port connectivity freight corridor (planned)', 'CR-VADHAVAN-SAMRUDDHI', NULL, 'State (Maharashtra)', 'Vadhavan Port (Palghar)', 'Samruddhi Expressway (junction not captured)', 105, '105 km (S041 headline)', NULL, NULL, 'Port-hinterland freight link', NULL, NULL, 'REPORTED', '2026-09-28');
INSERT INTO project_aliases (project_id, alias, alias_norm) VALUES
  ('ITI-P-0016', 'Vadhavan Port–Samruddhi Expressway Freight Corridor', 'vadhavan port samruddhi expressway freight corridor'),
  ('ITI-P-0016', 'Vadhavan–Samruddhi connector', 'vadhavan samruddhi connector');
INSERT INTO project_states (project_id, state_code, is_primary) VALUES
  ('ITI-P-0016', 'IN-MH', true);
INSERT INTO project_events (project_id, event_date, date_precision, event_type, status_code, description, record_confidence, source_id) VALUES
  ('ITI-P-0016', '2025-08-05', 'day', 'approval', 'APPROVED', 'Approved by Maharashtra Cabinet', 'REPORTED', 'S041');
INSERT INTO project_updates (project_id, as_of_date, as_of_precision, physical_pct, note, source_id) VALUES
  ('ITI-P-0016', '2025-08-05', 'day', 0, NULL, 'S041');
INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES ('ITI-P-0016', 'centroid', ST_GeomFromText('POINT(72.66 19.93)', 4326), 'APPROXIMATE', 'Vadhavan port locality only; alignment unknown', true);
INSERT INTO opportunity_signals (project_id, category, signal_type, signal_date, description, source_id, last_verified) VALUES
  ('ITI-P-0016', 'TENDER_EXPECTED', 'Cabinet approval', '2025-08-05', 'State cabinet approval 5 Aug 2025. Procurement timing not documented.', 'S041', '2026-09-28');
COMMIT;
