#!/usr/bin/env node
/*
 * Builds dashboard/data/india-states.js from a state-boundary GeoJSON.
 * Source used for the prototype: DataMeet India "states.geojson"
 *   https://github.com/datameet/maps  (CC BY 4.0, attribution required)
 * Usage: node tools/build-basemap.js <states.geojson> [tolerance_deg=0.02]
 * Output rings are [lng,lat] rounded to 3 dp after Douglas–Peucker simplification.
 * PRODUCTION NOTE: replace with Survey of India–compliant boundaries (see docs).
 */
const fs = require("fs");
const path = require("path");
const [, , input, tolArg] = process.argv;
if (!input) { console.error("usage: build-basemap.js <states.geojson> [tol]"); process.exit(1); }
const tol = Number(tolArg || 0.02);

function perpDist(p, a, b) {
  const [x, y] = p, [x1, y1] = a, [x2, y2] = b;
  const dx = x2 - x1, dy = y2 - y1;
  if (dx === 0 && dy === 0) return Math.hypot(x - x1, y - y1);
  const t = Math.max(0, Math.min(1, ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy)));
  return Math.hypot(x - (x1 + t * dx), y - (y1 + t * dy));
}
function simplify(pts) {
  if (pts.length < 4) return pts;
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [s, e] = stack.pop(); let idx = -1, max = 0;
    for (let i = s + 1; i < e; i++) { const d = perpDist(pts[i], pts[s], pts[e]); if (d > max) { max = d; idx = i; } }
    if (max > tol) { keep[idx] = 1; stack.push([s, idx], [idx, e]); }
  }
  return pts.filter((_, i) => keep[i]);
}
const NAME_FIX = { "Arunanchal Pradesh": "Arunachal Pradesh", "NCT of Delhi": "Delhi", "Andaman & Nicobar Island": "Andaman & Nicobar Islands", "Dadara & Nagar Havelli": "Dadra & Nagar Haveli" };
const g = JSON.parse(fs.readFileSync(input, "utf8"));
const out = g.features.map((f) => {
  const raw = f.properties.ST_NM || f.properties.st_nm || f.properties.NAME_1;
  const polys = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates;
  const rings = [];
  for (const poly of polys) {
    const outer = simplify(poly[0]).map(([x, y]) => [+x.toFixed(3), +y.toFixed(3)]);
    if (outer.length >= 4) rings.push(outer);
  }
  return { name: NAME_FIX[raw] || raw, rings };
});
const dest = path.join(__dirname, "..", "dashboard", "data", "india-states.js");
fs.writeFileSync(dest,
  "/* India state boundaries — simplified from DataMeet India maps (CC BY 4.0), https://github.com/datameet/maps.\n" +
  " * Prototype basemap only. Boundary file predates the 2019 J&K / Ladakh reorganisation; both are drawn as one unit.\n" +
  " * Production must use Survey of India–compliant boundaries. Generated by tools/build-basemap.js */\n" +
  "window.ITIS_BASEMAP = " + JSON.stringify(out) + ";\n");
console.log("wrote", dest, (fs.statSync(dest).size / 1024).toFixed(0) + " KB", out.length, "states");
