#!/usr/bin/env node
/*
 * Generates db/seed_sample.sql from dashboard/data/sample-data.js so the
 * relational schema (db/schema.sql) and the dashboard share one dataset.
 * Usage: node tools/build-seed.js
 */
const fs = require("fs");
const path = require("path");
global.window = {};
require(path.join(__dirname, "..", "dashboard", "data", "sample-data.js"));
const D = window.ITIS_DATA;

const q = (v) => (v == null ? "NULL" : typeof v === "number" ? String(v) : typeof v === "boolean" ? String(v) : "'" + String(v).replace(/'/g, "''") + "'");
const norm = (s) => s.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, " ").replace(/\b(limited|ltd|pvt|private|the)\b/g, "").replace(/\s+/g, " ").trim();
const slug = (s) => s.toUpperCase().replace(/[^A-Z0-9]+/g, "-").replace(/^-|-$/g, "");
// "2025" → year · "2025-06" → month · "2025-06-05" → day · anything else → unknown
function dt(s) {
  if (!s) return [null, "unknown"];
  const m = String(s).match(/^(\d{4})(?:-(\d{2}))?(?:-(\d{2}))?/);
  if (!m) return [null, "unknown"];
  return [`${m[1]}-${m[2] || "01"}-${m[3] || "01"}`, m[3] ? "day" : m[2] ? "month" : "year"];
}
const ISO = { "Delhi": "IN-DL", "Haryana": "IN-HR", "Rajasthan": "IN-RJ", "Madhya Pradesh": "IN-MP", "Gujarat": "IN-GJ", "Maharashtra": "IN-MH", "Karnataka": "IN-KA", "Andhra Pradesh": "IN-AP", "Tamil Nadu": "IN-TN", "Uttar Pradesh": "IN-UP", "Arunachal Pradesh": "IN-AR", "Jammu & Kashmir": "IN-JK", "Ladakh": "IN-LA", "Himachal Pradesh": "IN-HP", "Punjab": "IN-PB", "Goa": "IN-GA" };
const UT = new Set(["Delhi", "Jammu & Kashmir", "Ladakh"]);
const STATUS = [
  ["CONCEPT", "Concept / Proposed", "PRE", "PROPOSED"], ["FEASIBILITY", "Feasibility Study", "PRE", "PROPOSED"], ["DPR_PREPARATION", "DPR Preparation", "PRE", "PROPOSED"],
  ["DPR_COMPLETED", "DPR Completed", "PRE", "DPR"], ["CLEARANCES", "Environmental / Forest / Land Approval", "PRE", "APPROVED"], ["APPROVED", "Approved", "PRE", "APPROVED"],
  ["TENDER_EXPECTED", "Tender Expected", "PRE", "TENDERED"], ["TENDER_ISSUED", "Tender Issued", "PRE", "TENDERED"], ["BID_EVALUATION", "Bid Evaluation", "PRE", "TENDERED"],
  ["AWARDED", "Awarded", "PRE", "AWARDED"], ["LOA_ISSUED", "LOA Issued", "PRE", "AWARDED"], ["FC_PENDING", "Financial Closure Pending", "PRE", "APPROVED"],
  ["LAND_ACQUISITION", "Land Acquisition / Pre-Construction", "PRE", "APPROVED"], ["MOBILIZATION", "Mobilization", "CON", "CONSTRUCTION"], ["UNDER_CONSTRUCTION", "Under Construction", "CON", "CONSTRUCTION"],
  ["DELAYED", "Delayed", "CON", "CONSTRUCTION"], ["STALLED", "Stalled", "CON", "CONSTRUCTION"], ["PARTIALLY_OPERATIONAL", "Partially Operational", "CON", "CONSTRUCTION"],
  ["PACKAGE_WISE_CONSTRUCTION", "Package-wise Construction", "CON", "CONSTRUCTION"], ["SUBSTANTIALLY_COMPLETED", "Substantially Completed", "DONE", "COMPLETED"], ["COMPLETED", "Completed", "DONE", "COMPLETED"],
  ["OPERATIONAL", "Operational", "DONE", "OPERATIONAL"], ["OPEN_TO_TRAFFIC", "Open to Traffic", "DONE", "OPERATIONAL"], ["CANCELLED", "Cancelled", "OTHER", null],
  ["TERMINATED", "Terminated", "OTHER", null], ["RE_TENDERED", "Re-tendered", "OTHER", "TENDERED"], ["DISPUTED", "Disputed", "OTHER", null], ["UNKNOWN", "Unknown / Status Requires Verification", "OTHER", null],
];
function valueType(t) {
  const s = t.toLowerCase();
  if (s.startsWith("computed")) return "computed_sum";
  if (s.includes("sanction")) return "sanctioned";
  if (s.includes("expenditure")) return "expenditure_to_date";
  if (s.includes("increase") || s.includes("variation")) return "cost_variation";
  if (s.includes("revised")) return "revised";
  if (s.includes("headline")) return "headline";
  if (s.includes("budget")) return "budget_allocation";
  if (s.includes("award") || s.includes("contract")) return "award";
  if (s.includes("estimated") || s.includes("at start")) return "estimated";
  return "reported_cost";
}
const EVENT_TYPE = { APPROVED: "approval", AWARDED: "award", TENDER_ISSUED: "tender", BID_EVALUATION: "tender", RE_TENDERED: "re_tender", CANCELLED: "cancellation", DELAYED: "delay", OPERATIONAL: "opening", OPEN_TO_TRAFFIC: "opening", PARTIALLY_OPERATIONAL: "opening" };
const SIGNAL_TYPE = { TENDER_EXPECTED: "Cabinet approval", RE_TENDER: "Tender cancellation", CONSTRUCTION: "Construction milestone" };

const out = ["-- GENERATED by tools/build-seed.js from dashboard/data/sample-data.js — do not edit by hand.", "-- SAMPLE DATA: real projects, source-linked, not a complete database.", "SET search_path = itis, public;", "BEGIN;"];
const ins = (table, cols, rows) => rows.length && out.push(`INSERT INTO ${table} (${cols.join(", ")}) VALUES\n  ${rows.map((r) => "(" + r.map(q).join(", ") + ")").join(",\n  ")};`);

ins("lifecycle_status", ["code", "seq", "label", "phase", "pipeline_stage"], STATUS.map((s, i) => [s[0], i + 1, s[1], s[2], s[3]]));
const stateNames = [...new Set(D.projects.flatMap((p) => p.states))];
ins("states", ["state_code", "name", "kind"], stateNames.map((n) => [ISO[n], n, UT.has(n) ? "Union Territory" : "State"]));
ins("sources", ["source_id", "url", "url_normalised", "title", "publisher", "source_type", "tier", "pub_date", "pub_date_precision", "access_date"],
  D.sources.map((s) => { const [d, p] = dt(s.pub_date); return [s.id, s.url, s.url.toLowerCase().replace(/\/+$/, ""), s.title, s.publisher, s.type, s.tier, d, p, s.access_date]; }));
// authorities: parents first
const auths = D.authorities.slice().sort((a, b) => (a.parent ? 1 : 0) - (b.parent ? 1 : 0));
ins("authorities", ["authority_id", "short_name", "legal_name", "level", "parent_authority_id", "website"], auths.map((a) => [a.id, a.short, a.name, a.level, a.parent, a.website]));
ins("authority_aliases", ["authority_id", "alias", "alias_norm"], D.authorities.flatMap((a) => [[a.id, a.short, norm(a.short)], [a.id, a.name, norm(a.name)]]));
ins("companies", ["company_id", "canonical_name", "listed", "country", "hq_city", "website", "kind"], D.companies.map((c) => [c.id, c.name, c.listed, c.country, c.hq, c.website, c.kind]));
const aliasRows = []; D.companies.forEach((c) => { const seen = new Set(); [c.name, ...c.aliases].forEach((a) => { const k = norm(a); if (k && !seen.has(k)) { seen.add(k); aliasRows.push([c.id, a, k]); } }); });
ins("company_aliases", ["company_id", "alias", "alias_norm"], aliasRows);
const corridors = [...new Set(D.projects.map((p) => p.corridor))];
ins("corridors", ["corridor_id", "name"], corridors.map((c) => ["CR-" + slug(c), c]));

D.projects.forEach((p) => {
  out.push(`\n-- ${p.id} ${p.name}`);
  ins("projects", ["project_id", "canonical_name", "project_type", "category", "corridor_id", "highway_no", "programme", "origin", "destination", "length_km", "length_basis", "lanes", "terrain", "strategic_importance", "nodal_ministry_id", "implementing_authority_id", "record_confidence", "last_verified"],
    [[p.id, p.name, p.type, p.category, "CR-" + slug(p.corridor), p.highway_no, p.program, p.origin, p.destination, p.length_km, p.length_note, p.lanes, p.terrain, p.strategic, p.nodal_ministry, p.authority_id, p.confidence, p.last_verified]]);
  const al = new Map(); [p.name, ...p.aliases].forEach((a) => al.set(norm(a), a));
  ins("project_aliases", ["project_id", "alias", "alias_norm"], [...al].map(([k, a]) => [p.id, a, k]));
  ins("project_states", ["project_id", "state_code", "is_primary"], p.states.map((s) => [p.id, ISO[s], s === p.primary_state]));
  p.packages.forEach((k) => {
    const pkgRef = `(SELECT package_id FROM packages WHERE project_id=${q(p.id)} AND package_no=${q(k.no)})`;
    out.push(`INSERT INTO packages (project_id, package_no, name, length_km, progress_pct, progress_asof, record_confidence, source_id) VALUES (${[p.id, k.no, k.name, k.length_km, k.progress_pct == null ? null : k.progress_pct].map(q).join(", ")}, ${k.progress_pct == null ? "NULL" : q(dt(p.progress.asof)[0])}, ${q(k.confidence)}, ${q(k.source)});`);
    if (!k.contractor) return;
    const [ad, ap] = dt(k.award_date);
    const status = k.status === "COMPLETED" ? "completed" : ["UNDER_CONSTRUCTION", "MOBILIZATION"].includes(k.status) ? "active" : null;
    out.push(`WITH c AS (INSERT INTO contracts (package_id, contract_type, award_date, award_date_precision, award_value_cr, contract_status, record_confidence, source_id) VALUES (${pkgRef}, 'Unknown', ${q(ad)}, ${q(ap)}, ${q(k.value_cr)}, ${q(status)}, ${q(k.confidence)}, ${q(k.source)}) RETURNING contract_id)\n` +
      `INSERT INTO contract_parties (contract_id, company_id, role, share_pct, original_name_in_source, record_confidence, source_id) SELECT contract_id, v.* FROM c, (VALUES ${k.contractor.members.map((m, i) => "(" + [m.company, k.contractor.kind === "JV" ? (i === 0 && m.role === "JV lead" ? "JV lead" : m.role.startsWith("Consortium") ? "Consortium member" : "JV member") : "Sole contractor", m.share == null || k.contractor.kind !== "JV" ? null : m.share, D.companies.find((c) => c.id === m.company).name, k.confidence, k.source].map((v, j) => (j === 2 ? (v == null ? "NULL::numeric" : v) : j === 4 ? q(v) + "::itis.confidence_level" : q(v))).join(", ") + ")").join(", ")}) AS v;`);
  });
  ins("project_values", ["project_id", "value_cr", "value_type", "value_type_detail", "as_of_date", "as_of_precision", "is_reference", "reference_reason", "discrepancy_note", "record_confidence", "source_id"],
    p.values.map((v, i) => { const [d, pr] = dt(v.date); return [p.id, v.value_cr, valueType(v.type), v.type, d, pr, !!v.ref, v.ref ? (v.computed ? "No whole-project figure reported; sum of section costs" : "Most specific whole-project cost reported") : null, i === 0 ? p.value_conflict || null : null, v.confidence, v.source]; }));
  ins("project_events", ["project_id", "event_date", "date_precision", "event_type", "status_code", "description", "record_confidence", "source_id"],
    p.events.map((e) => { const [d, pr] = dt(e.date); return [p.id, d, pr, e.status ? EVENT_TYPE[e.status] || "status_change" : "milestone", e.status, e.event, "REPORTED", e.source]; }));
  if (p.progress && (p.progress.physical_pct != null || p.progress.note)) {
    const [d, pr] = dt(p.progress.asof);
    if (d) ins("project_updates", ["project_id", "as_of_date", "as_of_precision", "physical_pct", "note", "source_id"], [[p.id, d, pr, p.progress.physical_pct, p.progress.note || null, p.status_source]]);
  }
  ins("delay_risks", ["project_id", "category", "description", "source_id"], p.risks.map((r) => [p.id, r.category, r.text, r.source]));
  const c = p.geom.coords.map(([la, lo]) => `${lo} ${la}`);
  const wkt = p.geom.kind === "point" ? `POINT(${c[0]})` : `LINESTRING(${c.join(", ")})`;
  out.push(`INSERT INTO project_locations (project_id, role, geom, precision, basis, is_planned) VALUES (${q(p.id)}, ${q(p.geom.kind === "point" ? "centroid" : "schematic")}, ST_GeomFromText(${q(wkt)}, 4326), 'APPROXIMATE', ${q(p.geom.basis)}, ${!!p.geom.planned});`);
  ins("technology_requirements", ["project_id", "domain", "kind", "basis"], p.tech.map((t) => [p.id, t.domain, t.kind, t.basis]));
  if (p.opportunity) { const [d] = dt(p.opportunity.asof); ins("opportunity_signals", ["project_id", "category", "signal_type", "signal_date", "description", "source_id", "last_verified"], [[p.id, p.opportunity.category, (p.opportunity.category === "RE_TENDER" && !/cancel/i.test(p.opportunity.signal) ? "Other" : SIGNAL_TYPE[p.opportunity.category] || "Other"), d, p.opportunity.signal, p.opportunity.source, p.last_verified]]); }
});
out.push("COMMIT;");
const dest = path.join(__dirname, "..", "db", "seed_sample.sql");
fs.writeFileSync(dest, out.join("\n") + "\n");
console.log("wrote", dest);
